### ISSUE TITLE
Race conditions with setting machine storage

### ISSUE THREAD

**Issue by FrederoxDev** [Fluffyalien1422/bedrock-energistics-core#68]
Currently the only way that I have found to make machine storages (e.g. batteries) has a fatal flawed approach, with using this code below:
```
setMachineStorage(ev.block, "energy", realEnergy - amountToSend);
generate(ev.block, "energy", amountToSend);
```

These two functions have no guaranteed order, and can lead to race conditions such as:

- both set and generate are called
- the handlers are invoked on the core side
- the handler for the generate precise seems to go first and reads the value of the storage type before set has actually written the value
- set then finally finishes
- generate then happens whenever we run the network send func, it restores the amount before the set was called and then adds its own generated amount ontop, effectively doubling the amount in the machine (assuming its a low priority consumer with nothing consuming on the network)

**Comment by Fluffyalien1422** [comment]
Why are you calling `setMachineStorage`? `generate` should remove whatever is used automatically. You only need to call `generate(block, "energy", 0)`

**Comment by FrederoxDev** [comment]
generate does that? huh okay, I'll look into that when I head on next, thanks

**Comment by FrederoxDev** [comment]
I'm not entirely sure why this was closed, and I dont have the permissions to reopen it, I mean looking into it, thats not how generate works? There is nothing in the code that does that

```
export function generateListener(payload: ipc.SerializableValue): null {
  const data = payload as MangledGeneratePayload;
  const location = deserializeDimensionLocation(data.a);
  const type = data.b;
  const amount = data.c;

  const block = location.dimension.getBlock(location);
  if (!block) return null;

  const fullAmount = amount + getMachineStorage(location, type);
  if (!fullAmount) return null;

  const storageType = InternalRegisteredStorageType.forceGetInternal(type);

  MachineNetwork.getOrEstablish(storageType.category, block)?.queueSend(
    block,
    type,
    fullAmount,
  );

  return null;
}
```

It simply queues sending the amount in the machine already plus the amount to generate, 

At no point in the *send generator does it take away the energy either.

**Comment by FrederoxDev** [comment]
Also thats not the best behaviour for generate I just realised? Its not ideal for it to do that because in the scenario where you want a machine to have a limited rate output, this doesn't work because it adds on the amount stored inside

**Comment by FrederoxDev** [comment]
That's not it, that's the line that handles sending power to machines, not take power out of a machine after using the generate function.

**Comment by Fluffyalien1422** [comment]
> Nope that's not it, that's the line that handles sending power to machines, not take power out of a machine after using the generate function, that behavior did not exist until my latest PR that is currently open :p

What? Did you even test it before making your PR?

> I also know for a fact that it works because all Bedrock Energistics generators rely on this behavior.
